import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib

from ml_platform.core.exceptions import ModelUnavailableError


@dataclass
class LoadedModel:
    pipeline: Any
    metadata: dict[str, Any]


def load_model(model_path: Path, metadata_path: Path) -> LoadedModel:
    if not model_path.is_file() or not metadata_path.is_file():
        raise ModelUnavailableError("verified model artifact or metadata is missing")
    try:
        # Only load artifacts generated by this trusted training pipeline.
        model = joblib.load(model_path)
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ModelUnavailableError("model artifact could not be loaded") from exc
    return LoadedModel(model, metadata)
